### ISSUE TITLE
Filter premature predictions from the feed

### ISSUE THREAD

**Issue by laaksma** [HSLdevcom/transitdata-tripupdate-processor#12]
In some cases the departure event can trigger prematurely for the first stop of a trip. This happens when the vehicle's gps position exits the stop area temporarily due to vehicle movement or an erroneous signal. This causes StopTimeUpdates to be generated for each stop of the trip, with times predicted as if the vehicle had already departed. We need to filter out these erroneous, too early predictions.

**Comment by paasovaara** [comment]
https://github.com/HSLdevcom/transitdata-tripupdate-processor/commit/61e7cb465e5718be2a23fc4fa3e5d10d5cb1142b
