### ISSUE TITLE
Refactor Stop Events to a independent component

### ISSUE THREAD

**Issue by laaksma** [HSLdevcom/transitdata-tripupdate-processor#40]
Currently Trip update processor ingests messages of type Arrival and Departure, which are Pubtrans data types. We'd want to move the processing logic for these types to a separate service which handles the raw data and produces smaller Stop Time Estimate (name tbd) type messages.
The content would be roughly:
- date
- route
- direction
- trip start time
- stop id
- type (arrival or departure)
- estimated time
- timetabled time
- generation time stamp

This would allow us to use different data sources in the future, and also simplify the analytics related to the estimates.

**Comment by paasovaara** [comment]
additional fields needed for TripUpdates
- stopSeq
- scheduledRelationship (scheduled / cancelled) 

we also need to define a unique trip key (ID)
What to use as Pulsar key?

**Comment by paasovaara** [comment]
all else are required fields except "timetabled-time" which is optional

**Comment by paasovaara** [comment]
format in this phase is Jore (direction).

perhaps namespace the fields to be jore-direction, jore-route, etc. ?

**Comment by paasovaara** [comment]
reviewing: https://www.digitraffic.fi/rautatieliikenne/#junat
some things need to be mapped but overall should work? if liveEstimateTime is missing we just filter those ones out,?

**Comment by paasovaara** [comment]
let's add trip-id to the payload. we'll use this as unique key for this trip. String as data type so it's easily extendable.

**Comment by paasovaara** [comment]
this is now fully merged to develop
