### ISSUE TITLE
Directions with trip cancellations are in wrong format

### ISSUE THREAD

**Issue by laaksma** [HSLdevcom/transitdata-tripupdate-processor#42]
Trip cancellation messages have their direction ids in Jore format (1 or 2) and they should be reformatted for GTFS format (0 or 1). See https://github.com/HSLdevcom/transitdata-tripupdate-processor/blob/develop/src/main/java/fi/hsl/transitdata/tripupdate/gtfsrt/GtfsRtFactory.java#L80

**Comment by paasovaara** [comment]
fixed in develop
