### ISSUE TITLE
Handle via points in StopTimeUpdates

### ISSUE THREAD

**Issue by laaksma** [HSLdevcom/transitdata-tripupdate-processor#9]
The Pubtrans Arrival and Departure data sources contain a special case of JourneyPatternPoints called via points. The are functionally similar to stops, except they are visible only to the vehicle's onboard computer. Via points are used to improve the positioning accuracy.

1. We need to remove the via points from the StopTimeUpdate lists, as we do not want to show arrival and departure time predictions for via points to our end users.
2. We need to remove the stop sequence numbering from the StopTimeUpdate lists, as the numbering in the source data takes into account the via points, whereas the static GTFS data does not. The numbering has to be the same in both data sets.
2.1. A special case is a trip where the bus visits the same stop more than once during the trip. In this case we do need the stop sequence number to disambiguate which stop event the prediction concerns.

**Comment by paasovaara** [comment]
@laaksma how can we implement part 1? is there a way to distinguish via point?

**Comment by paasovaara** [comment]
fixed and merged
